# Generated by Django 5.1.3 on 2024-11-30 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100)),
                ('dish_description', models.TextField()),
                ('cuisine_category', models.JSONField()),
                ('food_category', models.CharField(max_length=50)),
                ('timing_category', models.JSONField(default=list)),
                ('meal_category', models.JSONField(default=list)),
                ('cooking_method', models.JSONField(default=list)),
                ('cooking_time', models.CharField(max_length=50)),
                ('cooking_temperature', models.CharField(max_length=50)),
                ('serving_size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_range', models.IntegerField(blank=True, help_text='Start of the range (optional).', null=True)),
                ('end_range', models.IntegerField(blank=True, help_text='End of the range (optional).', null=True)),
                ('qr_value', models.CharField(blank=True, help_text='Enter a single value (optional).', max_length=255, null=True)),
                ('qr_code_data', models.TextField(blank=True, help_text='Generated QR code data.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when the QR code was created.')),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(max_length=50, unique=True)),
                ('restaurant_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CookingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('step_description', models.TextField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitshield_webapp.dish')),
            ],
        ),
        migrations.CreateModel(
            name='AllergicContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(max_length=100)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitshield_webapp.dish')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitshield_webapp.dish')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitshield_webapp.restaurant'),
        ),
    ]
