# Generated by Django 5.1.3 on 2025-02-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitshield_webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergiccontent',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='cookingstep',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='dish',
        ),
        migrations.DeleteModel(
            name='QRCode',
        ),
        migrations.DeleteModel(
            name='AllergicContent',
        ),
        migrations.DeleteModel(
            name='CookingStep',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
