"""
Django settings for fitshield project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
# from dotenv import load_env
import os
from datetime import datetime

from dotenv import load_dotenv
from fitshield_webapp.utils.logging_utils import get_dynamic_log_path


load_dotenv()

# Dish Verification Filter 
MIN_DISH_LEVEL = os.getenv("MIN_DISH_LEVEL", "unverified") 
print(f"MIN_DISH_LEVEL:{MIN_DISH_LEVEL}")


BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-c9#%b@&0q45+uivi9u%4^kowrxzdm$=5*!p3rcvj5gk_4q+!oa'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fitshield_webapp.apps.FitshieldWebappConfig',
    'corsheaders',
    'rest_framework',
    'background_task',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True


CORS_ALLOWED_ORIGINS = [
    # '*',
    'http://localhost:8080',
    'http://192.168.1.17:8000',  
    'http://192.168.1.17:8080',  
    'http://192.168.1.53:8000', 
    'http://192.168.1.54:8000',
    'http://192.168.1.37:8000', 
    'http://192.168.1.11:8000', 
     'http://192.168.1.47:8000',
     'http://192.168.1.3:8000',
      'http://192.168.1.18:8000',
    'http://127.0.0.1:5000',
    'https://fitshield-7f442.web.app',
    'http://127.0.0.1:8000',
]

ALLOWED_HOSTS = ['.fitshield.in', '127.0.0.1', 'localhost' , "489e-2401-4900-8fc6-5a3f-2c5a-d80c-62d6-341c.ngrok-free.app"]

ROOT_URLCONF = 'fitshield.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fitshield.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Twilio Settings - Dharti Use
# TWILIO_ACCOUNT_SID = "ACf727a599e5924356634dd35cd971e039"  
# TWILIO_AUTH_TOKEN = "d363b1fcb6058780fd037ab47adbd127"  
# TWILIO_PHONE_NUMBER = "+14423003175"     

# Twilio Settings - Sharad Use
TWILIO_ACCOUNT_SID = "ACcaf15ae003d49089089f5c9bf441a597"  
TWILIO_AUTH_TOKEN = "890f31b0cfa836261fd702d31f41f369"    
TWILIO_PHONE_NUMBER = "+17692248577"    

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
# EMAIL_HOST_USER = '830296a08ed3cd'
# EMAIL_HOST_PASSWORD = 'c20ab16bd405cd'
# EMAIL_PORT = '587'
# EMAIL_USE_TLS = True
# DEFAULT_FROM_EMAIL = '830296a08ed3cd'

#Email setting
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com' 
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'partnerfitshield@gmail.com'
EMAIL_HOST_PASSWORD = 'gvdavjbyjsudqlex'
DEFAULT_FROM_EMAIL = 'partnerfitshield@gmail.com'


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'sandbox.smtp.mailtrap.io' 
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = '1f0bc72ae69fa5'
# EMAIL_HOST_PASSWORD = 'dc5db7569dc47c'
# DEFAULT_FROM_EMAIL = 'partnerfitshield@gmail.com'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com' 
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'dhartip.fitshield@gmail.com'
# EMAIL_HOST_PASSWORD = 'iovdifpubzbecvmi'
# DEFAULT_FROM_EMAIL = 'dhartip.fitshield@gmail.com'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.zoho.com' 
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'patner@fitshield.in'
# EMAIL_HOST_PASSWORD = 'JELZ55R8uEWG'
# DEFAULT_FROM_EMAIL = 'patner@fitshield.in'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

#AWS Connect - store image
AWS_ACCESS_KEY_ID = 'AKIAT5TW2LKXRYVGRHL3'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET = 'fitshield-data'
AWS_S3_REGION = 'ap-south-1'  
AWS_S3_CUSTOM_DOMAIN = f'https://restrurant.s3.amazonaws.com'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

#user pass

BASE_URL= "http://app.fitshield.in/#/splash"

# Add your OpenWeather API key here
WEATHER_API_KEY = "eb80b36af749d9cce199d32cf5af6375"
WEATHER_API_URL = "http://api.openweathermap.org/data/2.5/weather"


# Google API key here  
GENERATIVEAI_API_KEY ="AIzaSyC7PuTD0r_KKmKwqcnqpZTeA0-84bOSj24"

# PHONEPE 
PHONEPE_MERCHANT_ID = "FITSHIELDDIETFOODUAT"
PHONEPE_SALT_KEY = "689c1c1d-8185-40f6-876b-84257ad33f23"
PHONEPE_SALT_INDEX = "1"
PHONEPE_API_URL = "https://api-preprod.phonepe.com/apis/pg-sandbox"
PHONEPE_CALLBACK_URL = "https://489e-2401-4900-8fc6-5a3f-2c5a-d80c-62d6-341c.ngrok-free.app/api/callback"
PHONEPE_REDIRECT_URL = "https://489e-2401-4900-8fc6-5a3f-2c5a-d80c-62d6-341c.ngrok-free.app/api/callback"