swaps = {
    'Oil': ['Oil','Ghee', 'Olive Oil', 'Coconut Oil'],
    'Butter': ['Butter','Ghee', 'Plant-Based Spreads (Margarine, Avocado)', 'Olive Oil'],
    'Whole Milk': ['Whole Milk','Low-Fat Milk', 'Plant-Based Milk (Almond, Soy)', 'Buttermilk'],
    'Refined Sugar': ['Refined Sugar','Honey', 'Jaggery', 'Agave Syrup', 'Maple Syrup'],
    'Maida': ['Maida','Whole Wheat Flour', 'Multigrain Flour', 'Cassava Flour'],
    'White Rice': ['White Rice','Brown Rice', 'Quinoa', 'Millets (Sorghum, Pearl Millet)'],
    'Salt': ['Salt','Himalayan Pink Salt', 'Low-Sodium Salt', 'Sea Salt'],
    'Yogurt': ['Yogurt','Plant-Based Yogurt (Soy, Almond)', 'Coconut Milk Yogurt'],
    'Cream': ['Cream','Coconut Cream', 'Cashew Cream', 'Greek Yogurt'],
    'Cheese': ['Cheese','Plant-Based Cheese', 'Low-Fat Cheese', 'Ricotta'],
    'Meat': ['Meat','Lean Meat', 'Poultry', 'Plant-Based Proteins (Tofu, Seitan)'],
    'Fish': ['Fish','Lean Fish (Tilapia, Cod)', 'Plant-Based Fish Substitutes'],
    'Pasta': ['Pasta','Whole Wheat Pasta', 'Lentil Pasta', 'Zoodles (Vegetable Noodles)'],
    'Potatoes': ['Potatoes','Sweet Potatoes', 'Yams', 'Cauliflower'],
    'Bread': ['Bread','Whole Grain Bread', 'Sourdough', 'Multigrain Bread'],
    'Eggs': ['Eggs','Plant-Based Egg Replacers (Chickpea Flour, Flaxseed)'],
    'White Sugar': ['White Sugar','Coconut Sugar', 'Date Sugar', 'Stevia', 'Monk Fruit Sweetener'],
    'Soy Sauce': ['Soy Sauce','Tamari', 'Coconut Aminos', 'Low-Sodium Soy Sauce'],
    'Mayonnaise': ['Mayonnaise','Greek Yogurt', 'Avocado Spread', 'Hummus'],
    'Ketchup': ['Ketchup','Tomato Paste', 'Low-Sugar Ketchup', 'Fresh Salsa'],
    'Cornstarch': ['Cornstarch','Arrowroot Powder', 'Tapioca Starch', 'Potato Starch'],
    'White Vinegar': ['White Vinegar','Apple Cider Vinegar', 'Rice Vinegar', 'Lemon Juice'],
    'Soy Milk': ['Soy Milk','Almond Milk', 'Oat Milk', 'Rice Milk'],
    'Ground Beef': ['Ground Beef','Ground Turkey', 'Ground Chicken', 'Textured Vegetable Protein (TVP)'],
    'White Flour Tortillas': ['White Flour Tortillas','Whole Wheat Tortillas', 'Corn Tortillas', 'Lettuce Wraps'],
    'Heavy Cream': ['Heavy Cream','Evaporated Milk', 'Coconut Milk', 'Silken Tofu'],
    'Regular Pasta': ['Regular Pasta','Chickpea Pasta', 'Black Bean Pasta', 'Spiralized Vegetables'],
    'White Bread Crumbs': ['White Bread Crumbs','Panko', 'Almond Flour', 'Oats'],
    'Corn Syrup': ['Corn Syrup','Honey', 'Maple Syrup', 'Agave Nectar'],
    'White Potatoes': ['White Potatoes','Cauliflower', 'Parsnips', 'Turnips'],
    'Coconut Milk': ['Coconut Milk','Almond Milk', 'Cashew Cream', 'Soy Cream'],
    'Peanut Butter': ['Peanut Butter','Almond Butter', 'Sunflower Seed Butter', 'Tahini'],
    'Breadcrumb Coating': ['Breadcrumb Coating','Crushed Nuts', 'Seed Mixes', 'Gluten-Free Crumbs'],
    'Eggs': [ 'Eggs','Flaxseed Meal', 'Chia Seeds', 'Aquafaba (Chickpea Water)'],
    'Cows Milk': ['Cows Milk','Almond Milk', 'Oat Milk', 'Coconut Milk'], #improvement as '
    'Wheat Flour': ['Wheat Flour','Rice Flour', 'Almond Flour', 'Buckwheat Flour'],
    'Butter': ['Butter','Margarine', 'Coconut Oil', 'Plant-Based Butter'],
    'Peanuts': ['Peanuts','Sunflower Seeds', 'Pumpkin Seeds', 'Tahini'],
    'Soy Sauce': ['Soy Sauce','Coconut Aminos', 'Worcestershire Sauce', 'Balsamic Vinegar'],
    'Eggs': ['Eggs','Flaxseed Meal', 'Chia Seeds', 'Applesauce'],
    'Cheese': ['Cheese','Nutritional Yeast', 'Vegan Cheese', 'Cashew Cheese'],
    'Tofu': ['Jackfruit', 'Hearts of Palm', 'Tofu'],
    'Tree Nuts': ['Tree Nuts','Sunflower Seeds', 'Pumpkin Seeds', 'Oats'],
    'Shellfish': ['Shellfish','Mushrooms', 'Firm Tofu', 'Artichoke Hearts'],
    'Gluten': ['Gluten','Cornstarch', 'Potato Starch', 'Arrowroot Powder'],
    'Honey': ['Honey','Agave Nectar', 'Maple Syrup', 'Date Syrup'],
    'Yogurt': ['Yogurt','Coconut Yogurt', 'Almond Yogurt', 'Cashew Yogurt'],
    'Mayonnaise': ['Mayonnaise','Avocado', 'Aquafaba Mayo', 'Hummus'],
    'Gelatin': ['Gelatin','Agar-Agar', 'Pectin', 'Carrageenan'],
    'Breadcrumbs': ['Breadcrumbs','Crushed Cornflakes', 'Rice Flour', 'Ground Almonds'],
    'Pasta': ['Pasta','Rice Noodles', 'Zucchini Noodles', 'Lentil Pasta'],
    'Cream': ['Cream','Coconut Cream', 'Cashew Cream', 'Soy Cream'],
    'Chicken': ['Chicken','Tempeh', 'Seitan', 'Jackfruit'],
    'Beef': ['Beef','Black Beans', 'Mushrooms', 'Lentils'],
    'Soy': ['Soy','Pea Protein', 'Chickpeas', 'Lupini Beans']
}